url: https://www.mapbox.com
api: https://www.mapbox.com/core
tileApi: https://api.mapbox.com
source: docs
permalink: /:categories/:title
baseurl: https://www.mapbox.com/mapbox-gl-js
highlighter: pygments
excerpt_separator: ""
version: v0.17.0
rdiscount:
  extensions: [smart]
exclude: [dist]
