url: https://www.mapbox.com
api: https://www.mapbox.com/core
tileApi: https://api.tiles.mapbox.com
source: docs
permalink: /:categories/:title
baseurl: /mapbox-gl-js
highlighter: pygments
excerpt_separator: ""
version: v0.6.0
rdiscount:
  extensions: [smart]
exclude: [dist]
