env: production
url: https://www.mapbox.com
api: https://www.mapbox.com/core
tileApi: https://api.mapbox.com
source: docs
permalink: /:categories/:title/
baseurl: https://www.mapbox.com/mapbox-gl-js
excerpt_separator: ""
exclude: [dist]
future: true
